import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { Main } from '../components/authentication';
import { useSession } from "next-auth/react";
import { useEffect } from 'react';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by Gabriel" />
        <link rel="icon" href="" />
      </Head>
      <Main/>
    </div>
  )
}

export default Home;
