import type { NextPage } from 'next';
import Head from 'next/head';

import { Main } from '../components/authentication';

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by Gabriel" />
        <link rel="icon" href="" />
      </Head>
      <Main/>
    </div>
  )
}

export default Home;
