import type { NextPage } from 'next';
import Head from 'next/head';
import { getSession } from "next-auth/react";
import { Post } from '../components/posts/index';

const Posts: NextPage = (props) => {
    console.log(props)
    return (
        <div>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by Gabriel" />
                <link rel="icon" href="" />
            </Head>
            <Post/>
        </div>
    )
}

export default Posts;


export async function getServerSideProps({ req }) {
    const session = await getSession({ req });
    if (!session) {
        return {
            redirect: {
                destination: '/',
                permanent: false
            }
        }
    }
    return {
        props: session.user
    }
}
  