import type { NextPage } from 'next';
import Head from 'next/head';
import { getSession } from 'next-auth/react';
import { clientPromise, db } from "./api/database/client";
//import Tasks from './api/database/schema/tasks';

import { Post } from '../components/posts';
import { Header } from '../components/posts/header';
import { List } from '../components/posts/list/';

const Posts: NextPage = ({user}) => {
    //console.log(user);
    return (
        <div>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by Gabriel" />
                <link rel="icon" href="" />
            </Head>
            <Header user={user}/>
            <Post/>
            <List user={user}/>
        </div>
    )
}

export default Posts;


export async function getServerSideProps({ req }) {
    try {
        const session = await getSession({ req });
        if (!session) {
            return {
                redirect: {
                    destination: '/',
                    permanent: false
                }
            }
        }
        clientPromise
        const findUser = await db.collection("users").findOne({email: session.user.email})
        /*
        const id = user?._id;
        const tasks = await db.collection("tasks").find({_id: id});
        console.log(tasks);
        */
        const convert = JSON.stringify(findUser);
        const user = JSON.parse(convert);
        return {
            props: {user}
        }
    } catch(err) {
        return {
            redirect: {
                destination: '/',
                permanent: false
            }
        }
    }
}
  