import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Query } from '../components/query';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Query</title>
        <meta name="description" content="Generated by Gabriel" />
        <link rel="icon" href="" />
      </Head>
      <Query/>
    </div>
  )
}

export default Home

export async function getServerSideProps(context) {
    console.log(context)
    return {
      props: {}
    }
}